### ISSUE TITLE
Unable to make an environment

### ISSUE THREAD

**Issue by QasimWani** [rte-france/Grid2Op#175]
## Environment
 - Grid2op version: `1.4.0`
 - numpy version: `1.20.2`
 - gym version: `0.15.4`
 - System: `osx`

## Bug description
Everytime I try to make the environment, I get the error (after it has finished downloading the data): `TypeError: expected dtype object, got 'numpy.dtype[float64]'`

### Code snippet

```python
import grid2op
env_name = 'l2rpn_case14_sandbox'
g2op_env = grid2op.make(env_name) # error after downloading the env.
```

## Current output

```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-8b9fd290a76d> in <module>
     10 with warnings.catch_warnings():
     11     warnings.filterwarnings("ignore")
---> 12     env = grid2op.make("rte_case14_realistic")
     13 
     14 class CustomRandom(RandomAgent):

~/opt/anaconda3/lib/python3.7/site-packages/grid2op/MakeEnv/Make.py in make(dataset, test, _add_to_name, **kwargs)
    293     if _aux_is_multimix(real_ds_path):
    294         make_from_path_fn = _aux_make_multimix
--> 295     return make_from_path_fn(dataset_path=real_ds_path, **kwargs)

~/opt/anaconda3/lib/python3.7/site-packages/grid2op/MakeEnv/MakeFromPath.py in make_from_dataset_path(dataset_path, _add_to_name, **kwargs)
    499                       opponent_budget_per_ts=opponent_budget_per_ts,
    500                       opponent_budget_class=opponent_budget_class,
--> 501                       kwargs_opponent=kwargs_opponent,
    502                       )
    503 

~/opt/anaconda3/lib/python3.7/site-packages/grid2op/Environment/Environment.py in __init__(self, init_grid_path, chronics_handler, backend, parameters, name, names_chronics_to_backend, actionClass, observationClass, rewardClass, legalActClass, voltagecontrolerClass, other_rewards, thermal_limit_a, with_forecast, epsilon_poly, tol_poly, opponent_action_class, opponent_class, opponent_init_budget, opponent_budget_per_ts, opponent_budget_class, opponent_attack_duration, opponent_attack_cooldown, kwargs_opponent, _raw_backend_class)
    118         self._init_backend(init_grid_path, chronics_handler, backend,
    119                            names_chronics_to_backend, actionClass, observationClass,
--> 120                            rewardClass, legalActClass)
    121 
    122     def get_path_env(self):

~/opt/anaconda3/lib/python3.7/site-packages/grid2op/Environment/Environment.py in _init_backend(self, init_grid_path, chronics_handler, backend, names_chronics_to_backend, actionClass, observationClass, rewardClass, legalActClass)
    161         # this is due to the class attribute
    162         self.backend.set_env_name(self.name)
--> 163         self.backend.load_grid(self._init_grid_path)  # the real powergrid of the environment
    164         self.backend.load_redispacthing_data(os.path.split(self._init_grid_path)[0])
    165         self.backend.load_grid_layout(os.path.split(self._init_grid_path)[0])

~/opt/anaconda3/lib/python3.7/site-packages/grid2op/Backend/PandaPowerBackend.py in load_grid(self, path, filename)
    247         self._iref_slack = None
    248         self._id_bus_added = None
--> 249         pp.runpp(self._grid, numba=numba_)
    250         if np.all(~self._grid.gen["slack"]):
    251             # there are not defined slack bus on the data, i need to hack it up a little bit

~/opt/anaconda3/lib/python3.7/site-packages/pandapower/run.py in runpp(net, algorithm, calculate_voltage_angles, init, max_iteration, tolerance_mva, trafo_model, trafo_loading, enforce_q_lims, check_connectivity, voltage_depend_loads, consider_line_temperature, run_control, **kwargs)
    223         _check_bus_index_and_print_warning_if_high(net)
    224         _check_gen_index_and_print_warning_if_high(net)
--> 225         _powerflow(net, **kwargs)
    226 
    227 

~/opt/anaconda3/lib/python3.7/site-packages/pandapower/powerflow.py in _powerflow(net, **kwargs)
     64 
     65     # convert pandapower net to ppc
---> 66     ppc, ppci = _pd2ppc(net)
     67 
     68     # store variables

~/opt/anaconda3/lib/python3.7/site-packages/pandapower/pd2ppc.py in _pd2ppc(net, sequence)
     79     else:
     80         # Calculates ppc1/ppc2 branch impedances from branch elements
---> 81         _build_branch_ppc(net, ppc)
     82 
     83     # Adds P and Q for loads / sgens in ppc['bus'] (PQ nodes)

~/opt/anaconda3/lib/python3.7/site-packages/pandapower/build_branch.py in _build_branch_ppc(net, ppc)
     49         _calc_line_parameter(net, ppc)
     50     if "trafo" in lookup:
---> 51         _calc_trafo_parameter(net, ppc)
     52     if "trafo3w" in lookup:
     53         _calc_trafo3w_parameter(net, ppc)

~/opt/anaconda3/lib/python3.7/site-packages/pandapower/build_branch.py in _calc_trafo_parameter(net, ppc)
    184     branch[f:t, F_BUS] = bus_lookup[trafo["hv_bus"].values]
    185     branch[f:t, T_BUS] = bus_lookup[trafo["lv_bus"].values]
--> 186     r, x, y, ratio, shift = _calc_branch_values_from_trafo_df(net, ppc)
    187     branch[f:t, BR_R] = r
    188     branch[f:t, BR_X] = x

~/opt/anaconda3/lib/python3.7/site-packages/pandapower/build_branch.py in _calc_branch_values_from_trafo_df(net, ppc, trafo_df)
    250     vn_trafo_hv, vn_trafo_lv, shift = _calc_tap_from_dataframe(net, trafo_df)
    251     ratio = _calc_nominal_ratio_from_dataframe(ppc, trafo_df, vn_trafo_hv, vn_trafo_lv,
--> 252                                                bus_lookup)
    253     r, x, y = _calc_r_x_y_from_dataframe(net, trafo_df, vn_trafo_lv, vn_lv, ppc)
    254     return r, x, y, ratio, shift

~/opt/anaconda3/lib/python3.7/site-packages/pandapower/build_branch.py in _calc_nominal_ratio_from_dataframe(ppc, trafo_df, vn_hv_kv, vn_lv_kv, bus_lookup)
    442     hv_bus = get_trafo_values(trafo_df, "hv_bus")
    443     lv_bus = get_trafo_values(trafo_df, "lv_bus")
--> 444     nom_rat = get_values(ppc["bus"][:, BASE_KV], hv_bus, bus_lookup) / \
    445               get_values(ppc["bus"][:, BASE_KV], lv_bus, bus_lookup)
    446     return tap_rat / nom_rat

TypeError: expected dtype object, got 'numpy.dtype[float64]'
```

## Expected output

```
You may now use the environment "l2rpn_case14_sandbox" with the available data by invoking:
	env = grid2op.make(`${env name}`)
```

**Comment by QasimWani** [comment]
Fixed it. creds: @BDonnot 
Problem coming from pandapower
downgrade `pandapower` to version `<1.20`
```python
import sys
!$sys.executable -m pip install -U "numpy<1.20"
```

**Comment by BDonnot** [comment]
TL,DR:
There are some compatibility issues between pandapower and numpy >= 1.2
(see https://github.com/e2nIEE/pandapower/issues/1146 )

At time of writing, they were not fixed, so we recommend to use numpy <1.20 (see code snippet above)
